# Use the official PostgreSQL image with a specific version
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 12345678


